theme: jekyll-theme-architect
title: "Understanding Global Trends for the Advancement of the Human Condition"
description: "This site hosts our CS 4641 Machine Learning group project @ Georgia Tech."
